- MANIFEST.in
Adds a MANIFEST.in file that allows config.yaml to be included in the pip install.
Fixes #42
> Add MANIFEST.in to include config.yaml

- casanovo/denovo/model.py
Correctly use `None` for an unspecified output path by default, otherwise the previous change on lines 138-139 doesn't work.
> Fix output path

- README.md
- casanovo/config.yaml
- casanovo/denovo/dataloaders.py
- casanovo/denovo/model.py
1. Harmonize default parameters in the code and in the config file, as per the discussion with Melih on Slack (Aug 6).
2. Simplify the examples to not use a config file. As sensible default values are used, we can simplify how most users will interact with Casanovo.
> Simplify config

- casanovo/denovo/evaluate.py
Don't crash when a prediction that's not found in the AA alphabet is encountered.
> Account for incorrect AAs during evaluation

- .github/workflows/tests.yml
- casanovo/denovo/model.py
- tests/test_unit.py
Changed `tb_summarywriter` from `torch.utils.tensorboard.SummaryWriter` to `str` because we used to initialize the object in **config.py** but can't do this in **config.yaml**. Initialization now happens inside `Spec2Pep` if a folder path is passed.
> Pass folder path to initialize Tensorboard object

- .github/workflows/tests.yml
- README.md
- casanovo/casanovo.py
- casanovo/config.yaml
- casanovo/denovo/dataloaders.py
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
- casanovo/utils.py
- setup.cfg
- tests/conftest.py
- tests/test_integration.py
- tests/test_unit.py
* Download model weights from GitHub release
* Include dependencies
* Update model usage documentation
* Reformat with black
* Download weights to the OS-specific app dir
* Don't download weights if already in cache dir
* Update model file instructions
* Remove release notes from the README
We have this information on the Releases page now.
* Remove explicit model specification from example commands
* Harmonize default parameters and config values
As per discussion on Slack (https://noblelab.slack.com/archives/C01MXN4NWMP/p1659803053573279).
* No need to specify config file by default
This simplifies the examples that most users will want to use.
* Simplify version matching regex
* Remove depthcharge related tests
The transformer tests only deal with depthcharge functionality and just …
> Automatically download model weights (#68)

- tests/test_unit.py
Added a unit test for for peptide and amino acid-level evaluation metrics after reviewing `evaluate.py`.
> Add unit test for evaluation metrics

- CHANGELOG.md
- casanovo/denovo/model.py
Because beams can be terminated when the precursor mass is exceeded, peptide sequences might not necessarily end with a stop token.
Reported in #122.
> Check for stop token

- casanovo/denovo/evaluate.py
- casanovo/denovo/model.py
Minor PR addressing #112 which updates the printed evaluation metrics in the `eval` mode to agree with terms such as precision and coverage we use in the preprint and ICML paper.
> Align printed metrics with published terminology

- casanovo/config.yaml
- docs/getting_started.md
Addressing #29 , added comments to `config.yaml` and added a short explanation about the config file to read the docs. Indicated which parameters can be changed when running inference with Casanovo.
> Add documentation for config.yaml

- casanovo/denovo/model.py
- tests/test_unit.py
Output format is a `.csv` of lists of floats that correspond with the score between a spectra-peptide pair in the multi-annotated `.mgf`. It is always saved to `test.csv`.
> First Casanovo DB Search Iteration

- docs/getting_started.md
- setup.cfg
- In the _Getting Started_, clarify that optional PyTorch refers to automatic vs manual installation.
- Pin PyTorch Lightning to pre 2.0 to avoid installation conflicts.
Fixes #147.
> Clarify dependencies

- CHANGELOG.md
- casanovo/casanovo.py
- casanovo/config.yaml
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
- docs/getting_started.md
- setup.cfg
- tests/test_unit.py
Rather than simply modifying the peptide score to account for low-scoring stop tokens after very confident prefixes in low-ranking beams, I ended up refactoring the beam search and peptide caching functionality quite a bit.
- The score of the stop token is now included when calculating the peptide score. If no stop token is predicted, an additional "amino acid" with score `0` is added for the purpose of calculating the peptide score. (The score of the stop token is not reported in the mzTab output.)
- Rather than calculating the peptide score when evaluating the beam and when collecting the output, I removed this functionality duplication and compute the peptide score only once when evaluating the beam and then store it.
- This also moves the precursor m/z filter directly in the beam …
> Don't predict short peptides

- casanovo/denovo/model_runner.py
- docs/getting_started.md
Only a single worker thread is used for Apple MPS systems.
Fixes #109.
> Disable multithreading for MPS backend

- CHANGELOG.md
- pyproject.toml
Can be merged as soon as @wfondrie has released the new depthcharge version that incorporates the sinusoidal encodings fix.
> Upgrade depthcharge

- CHANGELOG.md
- casanovo/config.py
- casanovo/config.yaml
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
I put together this PR after coming to the conclusion that there was no option to run validation before a training epoch ends, which is crucial when training on large datasets like MSKB, but it also includes fixes to issues with logging and checkpointing we introduced earlier (1st commit: e11b80ada0e66f62a64fa880a33bdeb3865d99d1). To list the changes:
- `every_n_train_steps` option now controls both the frequency of validation epochs and model checkpointing. We can decouple the two but kept it as such for simplicity.
-  Validation performance metrics are logged (and added to tensorboard) at the validation epoch, and training loss is logged at the end of training epoch, i.e. training and validation metrics are logged asynchronously.
- We now log `step` rather than `epoch` as the unit of …
> Add validation frequency option 

- casanovo/casanovo.py
Old behavior:
- `--output foo.bar` -> `foo.log` and `foo.mztab`
- `--output foo.mztab` -> `foo.log` and `foo.mztab`
- `--output foo.log` -> `foo.log` and `foo.mztab`
New behavior:
- `--output foo.bar` -> `foo.bar.log` and `foo.bar.mztab`
- `--output foo.mztab` -> `foo.log` and `foo.mztab`
- `--output foo.log` -> `foo.log` and `foo.mztab`
> Only split off known extensions from output filename

- CHANGELOG.md
I have cherry-picked commits with bugfixes from `dev` into `main` to create a new release v3.4.0. Breaking changes, such as the DepthCharge upgrade and the `ModelRunner` change, have not been included yet and should wait until the major version upgrade to v4.
All tests work locally. The integration test doesn't work on GitHub Actions yet due to the known CPU bug that was fixed in 6299bd2 along with some breaking changes.
> Prepare for release v3.4.0

- casanovo/config.py
- casanovo/denovo/model_runner.py
Checkpointing during training can be enabled using the `logger` config option. If this is not specified, or during inference, don't create the `lightning_logs/` directory.
Fixes #187.
> Only create log directory when checkpointing is enabled

- casanovo/config.yaml
- casanovo/denovo/model.py
- tests/unit_tests/test_unit.py
And ensure that there are correct results when using only a single beam.
@melihyilmaz: Please include your unit tests for only a single beam on this branch.
> Use a single beam by default

- CHANGELOG.md
- casanovo/casanovo.py
> Nicely format logged warnings

- CHANGELOG.md
- casanovo/config.py
- casanovo/config.yaml
- casanovo/denovo/model_runner.py
- docs/faq.md
- tests/conftest.py
The option to configure the interval for validation and checkpointing has been changed:
- Config option `every_n_train_steps` has been renamed to `val_check_interval` in accordance to the corresponding Pytorch Lightning parameter.
- This now determines the number of training steps _across_ epochs instead of _within_ a single epoch. I.e. previously if there were 75,000 batches in the training data, validation would run at epoch=0,steps=50k; epoch=1,steps=50k; epoch=2,steps=50k; ...; whereas now it will run at epoch=0,steps=50k; epoch=1,steps=25k; epoch=1,steps=75k; ...
Fixes #211.
> Fix validation and checkpointing interval

- CHANGELOG.md
- casanovo/config.py
- tests/unit_tests/test_config.py
Custom residues in the config file were ignored, making it impossible to retrain Casanovo with now PTMs for example.
Fixes #228, fixes #227.
> Fix custom residues in config

- CHANGELOG.md
- casanovo/denovo/model.py
Forces gradient calculation during inference in order to prevent NaNs from being produced.
The line used: `with torch.set_grad_enabled(True):`
> Add lines to force gradient calculation.

- CHANGELOG.md
- casanovo/denovo/model.py
Fixes #252.
AA precision and recall were swapped due to swapped input of true and predicted peptides to the evaluation.
> Correctly report AA precision and recall during validation

- CHANGELOG.md
- casanovo/denovo/model.py
- pyproject.toml
This was a workaround to avoid NaN outputs. With PyTorch 2.10, the workaround is no longer necessary and local tests with [a setup that produces NaNs with older versions of PyTorch](https://github.com/Noble-Lab/casanovo/issues/186#issuecomment-1546112891) work correctly. 
Changes include:
- Removed gradient calculation in `validation_step()` and `predict_step()`
- Upgraded to PyTorch >= 2.1
> Remove gradient calculation during inference 

- docs/faq.md
> Document how to check that the GPU is used

- casanovo/config.py
- tests/unit_tests/test_config.py
- More efficient checking for unknown and missing config entries (no needless conversions/creations of sets and lists).
- Avoid creating temporary files in root directories during unit testing.
- Update outdated test.
This is a refactoring of #257.
> Check for invalid/missin config entries

- CHANGELOG.md
- casanovo/config.py
- casanovo/config.yaml
- casanovo/denovo/model_runner.py
- tests/conftest.py
- tests/unit_tests/test_runner.py
Instead of having to specify `train_from_scratch` in the config file, training will proceed from an existing model weights file if this is given as an argument to `casanovo train`.
Fixes #263.
> Remove `train_from_scratch` config option

- CHANGELOG.md
- casanovo/casanovo.py
- casanovo/config.py
- casanovo/data/datasets.py
- casanovo/data/ms_io.py
- casanovo/denovo/dataloaders.py
- casanovo/denovo/evaluate.py
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
- casanovo/utils.py
- casanovo/version.py
- docs/images/help.svg
- tests/conftest.py
- tests/unit_tests/test_config.py
- tests/unit_tests/test_runner.py
- tests/unit_tests/test_unit.py
Addresses #284 
To make sure we get the padding token at index  '0'  as the top scoring token for finished beams at each decoding step, I added a small epsilon of `1e-8` to index '0' in `finished_mask` so that it's not zeroed out like the rest of values on the same row. Again, these zero rows correspond to finished beams and we use masking to avoid extending them with new AA tokens.
This seems to resolve the error with minimal/no overhead (I get the same output on both CPU and GPU for the problematic mgf files mentioned in the issue) but unit tests still need to be added (@bittremieux feel free if you get a chance) and I'm open to moving away from `torch.topk()` if there are suggestions for a more robust or elegant solution.
> Stabilize torch.topk() behavior

- docs/faq.md
Supersedes #293 because I messed up. Because there was some categorization added to the FAQ I changed the merge point to `base` instead of `dev`, but that also pulled in changes in `dev` to `main`, which we only want to do as part of a new release. When changing back to `dev`, that then pulled changes from `main` to `dev`, which is also undesired. Tldr: I made a mess. Easier to quickly create a new PR.
I also removed the links to specific lines of code. When we make changes in this file the links wouldn't correspond with the latest code anymore, which might lead to confusion. Instead, power users that want to change the LR schedule should be able to find the appropriate location based on the provided description.
> Add FAQ on how to change the LR scheduler

- CHANGELOG.md
- pyproject.toml
Fixes #339.
Hotfix until NumPy v2.0 will be supported after the DepthCharge upgrade.
> Restrict NumPy to pre-2.0

- CHANGELOG.md
- casanovo/data/ms_io.py
Changed the charge value that's written to the results mzTab file to an integer value in order to comply with the mzTab standard.
> mzTab validation fix

- .github/workflows/tests.yml
Upgrade the Codecov version used in GitHub actions in order to resolve #363.
> Upgrade Codecove to v4

- casanovo/data/ms_io.py
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
- casanovo/utils.py
Created a data class for peptide spectrum matches, replacing the current tuple implementation in `MztabWriter`.
> PSM Data Class

- CHANGELOG.md
- casanovo/denovo/model.py
- tests/unit_tests/test_unit.py
Switched the peptide level score calculation from the arithmetic mean to the geometric mean of amino acid scores.
> Switched to Geometric Mean for Peptide Level Scores

- docs/index.md
- docs/nextflow.md
Added a Read the Docs page for the Casanovo Nextflow workflow.
> Casanovo Nextflow Workflow Documentation

- casanovo/denovo/model.py
- tests/unit_tests/test_unit.py
Fix for the reversed aa scores bug described in #408.
> Reversed peptide aa scores hotfix

- docs/applications.md
- docs/index.md
Added a new readthedocs page with links to papers using Casanovo, with one sentence descriptions for each.
Addresses issue #415
> Add documentation for applications of Casanovo

- tests/unit_tests/test_runner.py
Fixed windows test pipeline failure on `dev` branch.
> Windows test pipeline failure on `dev` branch fix

- CHANGELOG.md
- casanovo/casanovo.py
- docs/images/help.svg
Fixed issue where the suffix of the output root argument would get overridden, e.g. if output root is set to foo.bar the output files would become `foo.log` and `foo.mztab` rather than the expected `foo.bar.log` and `foo.bar.mztab`.
> Output root suffix fix

- .readthedocs.yml
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Specify Sphinx configuration for readthedocs

- docs/downstream_tools.md
Updated downstream tools to included dedicated Limelight section--removed some text from the Nextflow workflow section that was redundant with this new section.
> docs: update downstream tools to include dedicated Limelight section

- tests/conftest.py
- tests/test_integration.py
- tests/unit_tests/test_unit.py
Fixes #354.
This requires the DepthCharge upgrade (#350) before it will correctly function.
> Flexible format for scan titles

- casanovo/config.yaml
Marking as draft since Github tests are failing pending #480.
> Add Option to Disable Precursor Check
