Noble-Lab/casanovo

- README.md
> Document GPU out of memory error

- casanovo/casanovo.py
I forgot to harmonize changes across PRs for these two config values.
> Fix deleted config values

- README.md
- casanovo/casanovo.py
- casanovo/data/ms_io.py
- casanovo/denovo/model.py
- casanovo/denovo/model_runner.py
> Export to mzTab

- casanovo/denovo/model_runner.py
Fixes #50.
To be merged after [depthcharge#20](https://github.com/wfondrie/depthcharge/pull/20) has been integrated.
> Specify valid precursor charges

- casanovo/denovo/model_runner.py
Fix loading spectra from HDF5 files (missing `.` in the extension).
> Fix HDF5 extension

- CHANGELOG.md
Bump the CHANGELOG for the first PyPI release.
> Bump for first release

- codecov.yml
This PR requires that new PRs maintain or improve the coverage of unit / system tests.
> Enable and enforce codecov reports

- CHANGELOG.md
- casanovo/casanovo.py
- tests/test_unit.py
Small bugfix to not use model weights with an incorrect major version number.
> Fix weights version

- setup.cfg
Fix failing unit tests by adding the missing TensorBoard dependency.
> Fix unit tests

- README.md
- docs/index.md
- setup.cfg
> Preprint info

- docs/faq.md
> Describe which model weights file to use

- casanovo/denovo/model.py
- tests/test_unit.py
> Calculate AA scores as mean AA scores and peptide score

- docs/faq.md
> Add training data information

- docs/getting_started.md
> Note that inference should only use a single GPU

- casanovo/denovo/model.py
- Fixes minor issues in #165.
- Trivial refactoring to save space..
> Minor refactoring + issue fix

- docs/faq.md
> Add FAQ about using Casanovo for new PTMs

- CHANGELOG.md
- casanovo/config.yaml
- casanovo/denovo/model_runner.py
> Remove Pytorch Lightning logger

- CHANGELOG.md
- casanovo/denovo/model_runner.py
Fixes #216.
This issue was only present on `main`, not on `dev`. `dev` also includes relevant integration tests already.
> Fix running evaluation

- casanovo/denovo/model_runner.py
Add option to change label smoothing for model initialization from a checkpoint file.
> Minor fix to label smoothing

- casanovo/denovo/model.py
- tests/unit_tests/test_unit.py
Cherry picked aa scores hot-fix from main in order to add the fix to the dev branch as well.
> Reversed peptide aa scores hotfix (#417)

- docs/faq.md
> MassIVE-KB annotated MGF files on Zenodo

- casanovo/denovo/model.py
Workaround to fix issue described #461
> Depthcharge reverse detokinization bug work-around
